/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ConcernTree, ConsolidateRequest, ConsolidateResult, DiaryAppendRequest, DiaryAppendResult, DiaryEntry, ExperienceListFilter, ExperienceSnapshot, ExtractFactsRequest, ExtractFactsResult, ExtractionRecord, FactEntry, HumanAckDiaryRequest, HumanAddExperienceRequest, HumanAddFactRequest, HumanConfirmFactRequest, HumanDeleteConcernRequest, HumanDeleteExperienceRequest, HumanDeleteFactRequest, HumanEditExperienceRequest, HumanEditFactRequest, HumanPinRequest, HumanReleaseColdRequest, HumanSetConcernStatusRequest, IngestRequest, IngestResult, LedgerBlock, LedgerIntegrityResult, LedgerQueryRequest, MemoryExport, MemoryStats, MemoryWorkbenchInfo, RecallExperiencesRequest, RecallExperiencesResult, RefineExperienceRequest, RefineExperienceResult, ReportUseRequest, ReportUseResult, ReviseExperienceRequest, RollbackExperienceRequest, VerifyShadowRequest, VerifyShadowResult } from 'daoing-dsh-memory/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d656d6f7279 {
    appendDiary: (agentId: SessionId, request: DiaryAppendRequest) => Promise<RemoteResult<DiaryAppendResult>>
    consolidate: (agentId: SessionId, request: ConsolidateRequest) => Promise<RemoteResult<ConsolidateResult>>
    consolidationDue: (agentId: SessionId) => Promise<RemoteResult<{ due: boolean; lastTs: number; newSince: number; hoursSince: number; }>>
    exportLibrary: (agentId: SessionId) => Promise<RemoteResult<MemoryExport>>
    extract: (agentId: SessionId, request: ExtractFactsRequest) => Promise<RemoteResult<ExtractFactsResult>>
    extractionLog: (agentId: SessionId, limit: number, offset: number) => Promise<RemoteResult<ExtractionRecord[]>>
    extractionLogCount: (agentId: SessionId) => Promise<RemoteResult<number>>
    family: (agentId: SessionId, id: string) => Promise<RemoteResult<ExperienceSnapshot[]>>
    get: (agentId: SessionId, id: string, revision?: number) => Promise<RemoteResult<ExperienceSnapshot | undefined>>
    getDiaryByIds: (agentId: SessionId, ids: string[]) => Promise<RemoteResult<DiaryEntry[]>>
    humanAckDiary: (agentId: SessionId, request: HumanAckDiaryRequest) => Promise<RemoteResult<DiaryEntry>>
    humanAddExperience: (agentId: SessionId, request: HumanAddExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    humanAddFact: (agentId: SessionId, request: HumanAddFactRequest) => Promise<RemoteResult<FactEntry>>
    humanConfirmFact: (agentId: SessionId, request: HumanConfirmFactRequest) => Promise<RemoteResult<FactEntry>>
    humanDeleteConcern: (agentId: SessionId, request: HumanDeleteConcernRequest) => Promise<RemoteResult<{ deleted: true; }>>
    humanDeleteExperience: (agentId: SessionId, request: HumanDeleteExperienceRequest) => Promise<RemoteResult<{ deleted: true; }>>
    humanDeleteFact: (agentId: SessionId, request: HumanDeleteFactRequest) => Promise<RemoteResult<{ deleted: true; }>>
    humanEditExperience: (agentId: SessionId, request: HumanEditExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    humanEditFact: (agentId: SessionId, request: HumanEditFactRequest) => Promise<RemoteResult<FactEntry>>
    humanPin: (agentId: SessionId, request: HumanPinRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    humanPromote: (agentId: SessionId, id: string, reason: string) => Promise<RemoteResult<ExperienceSnapshot>>
    humanReleaseCold: (agentId: SessionId, request: HumanReleaseColdRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    humanRollback: (agentId: SessionId, request: RollbackExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    humanSetConcernStatus: (agentId: SessionId, request: HumanSetConcernStatusRequest) => Promise<RemoteResult<{ ok: true; }>>
    ingest: (agentId: SessionId, request: IngestRequest) => Promise<RemoteResult<IngestResult>>
    ledgerQuery: (agentId: SessionId, request: LedgerQueryRequest) => Promise<RemoteResult<LedgerBlock[]>>
    ledgerQueryCount: (agentId: SessionId, request: LedgerQueryRequest) => Promise<RemoteResult<number>>
    list: (agentId: SessionId, filter: ExperienceListFilter) => Promise<RemoteResult<ExperienceSnapshot[]>>
    listConcerns: (agentId: SessionId, kind: string, status: string, limit: number, offset: number) => Promise<RemoteResult<ConcernTree[]>>
    listConcernsCount: (agentId: SessionId, kind: string, status: string) => Promise<RemoteResult<number>>
    listDiary: (agentId: SessionId, limit: number, offset: number, onlyUnextracted: boolean) => Promise<RemoteResult<DiaryEntry[]>>
    listFacts: (agentId: SessionId, category: string, includeHistory: boolean, limit: number, offset: number) => Promise<RemoteResult<FactEntry[]>>
    listFactsCount: (agentId: SessionId, category: string, includeHistory: boolean) => Promise<RemoteResult<number>>
    recall: (agentId: SessionId, request: RecallExperiencesRequest) => Promise<RemoteResult<RecallExperiencesResult>>
    refine: (agentId: SessionId, request: RefineExperienceRequest) => Promise<RemoteResult<RefineExperienceResult>>
    report: (agentId: SessionId, request: ReportUseRequest) => Promise<RemoteResult<ReportUseResult>>
    revise: (agentId: SessionId, request: ReviseExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    rollback: (agentId: SessionId, request: RollbackExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    stats: (agentId: SessionId) => Promise<RemoteResult<MemoryStats>>
    verifyLedger: (agentId: SessionId) => Promise<RemoteResult<LedgerIntegrityResult>>
    verifyShadow: (agentId: SessionId, request: VerifyShadowRequest) => Promise<RemoteResult<VerifyShadowResult>>
    workbenchInfo: (agentId: SessionId) => Promise<RemoteResult<MemoryWorkbenchInfo>>
  }
  interface TypertRemoteMap {
    'memory/appendDiary': (agentId: SessionId, request: DiaryAppendRequest) => Promise<RemoteResult<DiaryAppendResult>>
    'memory/consolidate': (agentId: SessionId, request: ConsolidateRequest) => Promise<RemoteResult<ConsolidateResult>>
    'memory/consolidationDue': (agentId: SessionId) => Promise<RemoteResult<{ due: boolean; lastTs: number; newSince: number; hoursSince: number; }>>
    'memory/exportLibrary': (agentId: SessionId) => Promise<RemoteResult<MemoryExport>>
    'memory/extract': (agentId: SessionId, request: ExtractFactsRequest) => Promise<RemoteResult<ExtractFactsResult>>
    'memory/extractionLog': (agentId: SessionId, limit: number, offset: number) => Promise<RemoteResult<ExtractionRecord[]>>
    'memory/extractionLogCount': (agentId: SessionId) => Promise<RemoteResult<number>>
    'memory/family': (agentId: SessionId, id: string) => Promise<RemoteResult<ExperienceSnapshot[]>>
    'memory/get': (agentId: SessionId, id: string, revision?: number) => Promise<RemoteResult<ExperienceSnapshot | undefined>>
    'memory/getDiaryByIds': (agentId: SessionId, ids: string[]) => Promise<RemoteResult<DiaryEntry[]>>
    'memory/humanAckDiary': (agentId: SessionId, request: HumanAckDiaryRequest) => Promise<RemoteResult<DiaryEntry>>
    'memory/humanAddExperience': (agentId: SessionId, request: HumanAddExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'memory/humanAddFact': (agentId: SessionId, request: HumanAddFactRequest) => Promise<RemoteResult<FactEntry>>
    'memory/humanConfirmFact': (agentId: SessionId, request: HumanConfirmFactRequest) => Promise<RemoteResult<FactEntry>>
    'memory/humanDeleteConcern': (agentId: SessionId, request: HumanDeleteConcernRequest) => Promise<RemoteResult<{ deleted: true; }>>
    'memory/humanDeleteExperience': (agentId: SessionId, request: HumanDeleteExperienceRequest) => Promise<RemoteResult<{ deleted: true; }>>
    'memory/humanDeleteFact': (agentId: SessionId, request: HumanDeleteFactRequest) => Promise<RemoteResult<{ deleted: true; }>>
    'memory/humanEditExperience': (agentId: SessionId, request: HumanEditExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'memory/humanEditFact': (agentId: SessionId, request: HumanEditFactRequest) => Promise<RemoteResult<FactEntry>>
    'memory/humanPin': (agentId: SessionId, request: HumanPinRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'memory/humanPromote': (agentId: SessionId, id: string, reason: string) => Promise<RemoteResult<ExperienceSnapshot>>
    'memory/humanReleaseCold': (agentId: SessionId, request: HumanReleaseColdRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'memory/humanRollback': (agentId: SessionId, request: RollbackExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'memory/humanSetConcernStatus': (agentId: SessionId, request: HumanSetConcernStatusRequest) => Promise<RemoteResult<{ ok: true; }>>
    'memory/ingest': (agentId: SessionId, request: IngestRequest) => Promise<RemoteResult<IngestResult>>
    'memory/ledgerQuery': (agentId: SessionId, request: LedgerQueryRequest) => Promise<RemoteResult<LedgerBlock[]>>
    'memory/ledgerQueryCount': (agentId: SessionId, request: LedgerQueryRequest) => Promise<RemoteResult<number>>
    'memory/list': (agentId: SessionId, filter: ExperienceListFilter) => Promise<RemoteResult<ExperienceSnapshot[]>>
    'memory/listConcerns': (agentId: SessionId, kind: string, status: string, limit: number, offset: number) => Promise<RemoteResult<ConcernTree[]>>
    'memory/listConcernsCount': (agentId: SessionId, kind: string, status: string) => Promise<RemoteResult<number>>
    'memory/listDiary': (agentId: SessionId, limit: number, offset: number, onlyUnextracted: boolean) => Promise<RemoteResult<DiaryEntry[]>>
    'memory/listFacts': (agentId: SessionId, category: string, includeHistory: boolean, limit: number, offset: number) => Promise<RemoteResult<FactEntry[]>>
    'memory/listFactsCount': (agentId: SessionId, category: string, includeHistory: boolean) => Promise<RemoteResult<number>>
    'memory/recall': (agentId: SessionId, request: RecallExperiencesRequest) => Promise<RemoteResult<RecallExperiencesResult>>
    'memory/refine': (agentId: SessionId, request: RefineExperienceRequest) => Promise<RemoteResult<RefineExperienceResult>>
    'memory/report': (agentId: SessionId, request: ReportUseRequest) => Promise<RemoteResult<ReportUseResult>>
    'memory/revise': (agentId: SessionId, request: ReviseExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'memory/rollback': (agentId: SessionId, request: RollbackExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'memory/stats': (agentId: SessionId) => Promise<RemoteResult<MemoryStats>>
    'memory/verifyLedger': (agentId: SessionId) => Promise<RemoteResult<LedgerIntegrityResult>>
    'memory/verifyShadow': (agentId: SessionId, request: VerifyShadowRequest) => Promise<RemoteResult<VerifyShadowResult>>
    'memory/workbenchInfo': (agentId: SessionId) => Promise<RemoteResult<MemoryWorkbenchInfo>>
  }
  interface TypertRemoteNamespaceMap {
    'memory': TypertRemoteNamespace$6d656d6f7279
  }
  interface TypertRemoteScopeMap {
    'agent:memory/appendDiary': (request: DiaryAppendRequest) => Promise<RemoteResult<DiaryAppendResult>>
    'agent:memory/consolidate': (request: ConsolidateRequest) => Promise<RemoteResult<ConsolidateResult>>
    'agent:memory/consolidationDue': () => Promise<RemoteResult<{ due: boolean; lastTs: number; newSince: number; hoursSince: number; }>>
    'agent:memory/exportLibrary': () => Promise<RemoteResult<MemoryExport>>
    'agent:memory/extract': (request: ExtractFactsRequest) => Promise<RemoteResult<ExtractFactsResult>>
    'agent:memory/extractionLog': (limit: number, offset: number) => Promise<RemoteResult<ExtractionRecord[]>>
    'agent:memory/extractionLogCount': () => Promise<RemoteResult<number>>
    'agent:memory/family': (id: string) => Promise<RemoteResult<ExperienceSnapshot[]>>
    'agent:memory/get': (id: string, revision?: number) => Promise<RemoteResult<ExperienceSnapshot | undefined>>
    'agent:memory/getDiaryByIds': (ids: string[]) => Promise<RemoteResult<DiaryEntry[]>>
    'agent:memory/humanAckDiary': (request: HumanAckDiaryRequest) => Promise<RemoteResult<DiaryEntry>>
    'agent:memory/humanAddExperience': (request: HumanAddExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'agent:memory/humanAddFact': (request: HumanAddFactRequest) => Promise<RemoteResult<FactEntry>>
    'agent:memory/humanConfirmFact': (request: HumanConfirmFactRequest) => Promise<RemoteResult<FactEntry>>
    'agent:memory/humanDeleteConcern': (request: HumanDeleteConcernRequest) => Promise<RemoteResult<{ deleted: true; }>>
    'agent:memory/humanDeleteExperience': (request: HumanDeleteExperienceRequest) => Promise<RemoteResult<{ deleted: true; }>>
    'agent:memory/humanDeleteFact': (request: HumanDeleteFactRequest) => Promise<RemoteResult<{ deleted: true; }>>
    'agent:memory/humanEditExperience': (request: HumanEditExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'agent:memory/humanEditFact': (request: HumanEditFactRequest) => Promise<RemoteResult<FactEntry>>
    'agent:memory/humanPin': (request: HumanPinRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'agent:memory/humanPromote': (id: string, reason: string) => Promise<RemoteResult<ExperienceSnapshot>>
    'agent:memory/humanReleaseCold': (request: HumanReleaseColdRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'agent:memory/humanRollback': (request: RollbackExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'agent:memory/humanSetConcernStatus': (request: HumanSetConcernStatusRequest) => Promise<RemoteResult<{ ok: true; }>>
    'agent:memory/ingest': (request: IngestRequest) => Promise<RemoteResult<IngestResult>>
    'agent:memory/ledgerQuery': (request: LedgerQueryRequest) => Promise<RemoteResult<LedgerBlock[]>>
    'agent:memory/ledgerQueryCount': (request: LedgerQueryRequest) => Promise<RemoteResult<number>>
    'agent:memory/list': (filter: ExperienceListFilter) => Promise<RemoteResult<ExperienceSnapshot[]>>
    'agent:memory/listConcerns': (kind: string, status: string, limit: number, offset: number) => Promise<RemoteResult<ConcernTree[]>>
    'agent:memory/listConcernsCount': (kind: string, status: string) => Promise<RemoteResult<number>>
    'agent:memory/listDiary': (limit: number, offset: number, onlyUnextracted: boolean) => Promise<RemoteResult<DiaryEntry[]>>
    'agent:memory/listFacts': (category: string, includeHistory: boolean, limit: number, offset: number) => Promise<RemoteResult<FactEntry[]>>
    'agent:memory/listFactsCount': (category: string, includeHistory: boolean) => Promise<RemoteResult<number>>
    'agent:memory/recall': (request: RecallExperiencesRequest) => Promise<RemoteResult<RecallExperiencesResult>>
    'agent:memory/refine': (request: RefineExperienceRequest) => Promise<RemoteResult<RefineExperienceResult>>
    'agent:memory/report': (request: ReportUseRequest) => Promise<RemoteResult<ReportUseResult>>
    'agent:memory/revise': (request: ReviseExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'agent:memory/rollback': (request: RollbackExperienceRequest) => Promise<RemoteResult<ExperienceSnapshot>>
    'agent:memory/stats': () => Promise<RemoteResult<MemoryStats>>
    'agent:memory/verifyLedger': () => Promise<RemoteResult<LedgerIntegrityResult>>
    'agent:memory/verifyShadow': (request: VerifyShadowRequest) => Promise<RemoteResult<VerifyShadowResult>>
    'agent:memory/workbenchInfo': () => Promise<RemoteResult<MemoryWorkbenchInfo>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
