/**
 * Memory system wire vocabulary: experience lifecycle, recall adjudication,
 * use reports with attribution, the diary/fact semantic layer, and the
 * append-only ledger. Types only — no runtime code.
 * @module dsh-daoing-memory/types
 */
// ── experience lifecycle ────────────────────────────────────────────────────
/**
 * System-managed experience families that cannot be deleted by human operators
 * (only archived). The extraction-feedback family is auto-generated by the
 * daily deletion-reason summarizer and serves as negative guidance for future
 * memory extraction.
 */
export const SYSTEM_EXPERIENCE_FAMILIES = new Set([
    'extraction-feedback',
]);
/** Check whether an experience family is system-managed (delete-protected). */
export function isSystemExperienceFamily(family) {
    return SYSTEM_EXPERIENCE_FAMILIES.has(family);
}
//# sourceMappingURL=types.js.map